### ISSUE TITLE
Add const string to data section

### ISSUE THREAD

**Issue by tanishiking** [tanishiking/scala-wasm#18]
The current implementation stores constant strings in globals and sets those globals in the `start function`. However, it would be preferable to store those strings in the data section instead of as globals and instantiate them using `array.new_data`.

**Comment by sjrd** [comment]
Note: #19 contains a `createStringFromData` helper which we will probably need to implement this.

**Comment by tanishiking** [comment]
I was thinking that we could add constant string data into the data section of Wasm, and use `array.new_data` to instantiate it, and then create a string somehow.

However, we're using JavaScript String as an implementation, and WasmGC arrays are completely opaque to JavaScript (which means there's no way to construct a JavaScript String from WasmGC array directly). Therefore, we still need to loop over the array and use `charToString` for every element of the array even we add constant string into data 🤔 

How other languages handle string?
- Kotlin/Wasm implement String as a boxed WasmGC array
- [J2CL uses stringref](https://github.com/google/j2cl/blob/6dba605261b908df21234664960a5a05aa180c94/docs/getting-started-j2wasm.md?plain=1#L58-L61)

**Comment by sjrd** [comment]
Even if we have to loop with `charToString`, putting the strings in a data section would at least reduce the *size* of the .wasm file. Currently we're paying a lot of bytes of `instr` opcodes per produced `char`.
