### ISSUE TITLE
`tests/test` fails with `Unknown type code 0x4e, enable with --experimental-wasm-gc`

### ISSUE THREAD

**Issue by SethTisue** [tanishiking/scala-wasm#24]
```
tests.CoreTests:
==> X tests.CoreTests.testsuite.core.Simple 0.00s scala.scalajs.js.JavaScriptException: CompileError: WebAssembly.instantiate(): Unknown type code 0x4e, enable with --experimental-wasm-gc @+12
    at <jscode>.CompileError: WebAssembly.instantiate(): Unknown type code 0x4e, enable with --experimental-wasm-gc @+12(Unknown Source)
```

note that I know nothing — I'm just trying to clone the repo and run the tests

I did already do `NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly nvm install v22`

perhaps it's just a matter of needing to add `--experimental-wasm-gc` somewhere... but where?

**Comment by sjrd** [comment]
Does `node -v` actually print 22.xyz?

**Comment by tanishiking** [comment]
We need to run `nvm use 22` to switch node version to v22 (maybe we should add [.nvmrc](https://github.com/nvm-sh/nvm?tab=readme-ov-file#nvmrc) so that we can just run `NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly nvm install` + `nvm use` ?)

**Comment by SethTisue** [comment]
`nvm use 22` seems to have fixed it, so I guess that's the answer, but I'll leave the ticket open in case you want to add something to the readme or whatever

**Comment by tanishiking** [comment]
Added an instruction to run `nvm use 22` :+1:
