### ISSUE TITLE
Support `isInstanceOf[<interface>]`

### ISSUE THREAD

**Issue by tanishiking** [tanishiking/scala-wasm#27]
https://github.com/tanishiking/scala-wasm/blob/4643e4b9956e55dfff253e6da21e97a9b5ac6566/wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala#L1088-L1091

It required for supporting java.lang.Object's `clone` method (we also required to support `asInstanceOf[<interface>]`) and `throw` (that can be compiled to `unreachable` for now)
https://github.com/scala-js/scala-js/blob/80eafa9ecb54f6763c0df32350c9c6cd8e7343c5/project/JavaLangObject.scala#L93-L110

**Comment by tanishiking** [comment]
It can be checked at runtime by traversing the array of the itables

**Comment by sjrd** [comment]
Relevant paper: https://www.researchgate.net/publication/2438441_Efficient_Type_Inclusion_Tests/link/09e415145cfdf2dd95000000/download?_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6InB1YmxpY2F0aW9uIiwicGFnZSI6InB1YmxpY2F0aW9uIn19

**Comment by tanishiking** [comment]
Thanks!
I am going to implement by iterating the itables (which will be `O(N)` where `N` is the number of the interfaces the class implements) at this moment, but we definitely would like to move to constant-time (compressed) type inclusion test such as PE or BPE :+1:
I'm not sure which algorithm would be the best suite to us, but practically, either algorithms looks good.
