### ISSUE TITLE
Support Clone

### ISSUE THREAD

**Issue by tanishiking** [tanishiking/scala-wasm#34]
It might not be a feasible to support `Clone` on WasmGC because of it's lack of capability of deep copying the aggregated types in WasmGC (`struct.copy` and `array.copy` does that, but they're  in [Post-MVP](https://github.com/WebAssembly/gc/blob/main/proposals/gc/Post-MVP.md#sketch))

## Option 1: Implement deep copy
I couldn't find a way to implement because of `(difficulty 1)` 🤔 

- **(difficulty 1)** `A <: B` and `val x: A = new B(); x.clone()`, the `clone` method should create a new instance whose RTT (run-time-type) is `B`. However, we cannot compile to `struct.new $B` because we don't know it's RTT at compile-time.
- (difficulty 2) If we could solve `(difficulty 1)`, how do we copying over the each field to the new instance?
  - The only way is to `struct.get` from old instance and `struct.set` to the new instance. However, we don't know the runtime type (it's structure) of the old instance, in that case, how to `struct.get/set` all fields?
  - This could be solved by having an information about the runtime-type structure in `typeData`. For example, we can have a number of fields, then we can loop over all the fields.
    - https://github.com/tanishiking/scala-wasm/blob/099a72ea5aa09b4084338b0719efa03aa3d81a1b/wasm/src/main/scala/wasm4s/Wasm.scala#L90
- (difficulty 3) How to recursively deep copy? We should do the same thing to each field.
  - How about HijackedClasses (especially `byte`, `short`, `float`,  `double` and `string`)? We should do copy on JavaScript.

## Option 2: Drop Support for `Clone`
I'm not sure how the lack of `Clone` affects other part of implementation.

- (1) Compile `Clone` to `unreachable`. Easy, but it should be compilation failed if we use `clone`, instead of runtime.
- (2) Patch `java.lang.Object` to remove `clone`

It seems both `j2cl` and `Kotlin/Wasm` removes `clone` or `Cloneable` from IR.

**Comment by tanishiking** [comment]
It might not be a feasible to support `Clone` on WasmGC because of it's lack of capability of deep copying the aggregated types in WasmGC (`struct.copy` and `array.copy` does that, but they're  in [Post-MVP](https://github.com/WebAssembly/gc/blob/main/proposals/gc/Post-MVP.md#sketch))

## Option 1: Implement deep copy
I couldn't find a way to implement because of `(difficulty 1)` 🤔 

- **(difficulty 1)** `A <: B` and `val x: A = new B(); x.clone()`, the `clone` method should create a new instance whose RTT (run-time-type) is `B`. However, we cannot compile to `struct.new $B` because we don't know it's RTT at compile-time.
- (difficulty 2) If we could solve `(difficulty 1)`, how do we copying over the each field to the new instance?
  - The only way is to `struct.get` from old instance and `struct.set` to the new instance. However, we don't know the runtime type (it's structure) of the old instance, in that case, how to `struct.get/set` all fields?
  - This could be solved by having an information about the runtime-type structure in `typeData`. For example, we can have a number of fields, then we can loop over all the fields.
    - https://github.com/tanishiking/scala-wasm/blob/099a72ea5aa09b4084338b0719efa03aa3d81a1b/wasm/src/main/scala/wasm4s/Wasm.scala#L90
- (difficulty 3) How to recursively deep copy? We should do the same thing to each field.
  - How about HijackedClasses (especially `byte`, `short`, `float`,  `double` and `string`)? We should do copy on JavaScript.

## Option 2: Drop Support for `Clone`
I'm not sure how the lack of `Clone` affects other part of implementation.

- (1) Compile `Clone` to `unreachable`. Easy, but it should be compilation failed if we use `clone`, instead of runtime.
- (2) Patch `java.lang.Object` to remove `clone`

It seems both `j2cl` and `Kotlin/Wasm` removes `clone` or `Cloneable` from IR.

**Comment by sjrd** [comment]
`Clone` per se implements a *shallow* copy. If the user wants a deep copy for their `clone()` method, they must write additional logic in user code. This is inherited from Java. That removes difficulty 3.

For 1 and 2, the trick is to add a special `$clone` function pointer to the itable of `jl.Cloneable` (or the vtable of `jl.Object` if it's easier). We then generate the implementation for each concrete class that extends `Cloneable`. In that pseudo method, we statically know the exact `struct` type we need to generate with `new` and what its fields are.
