### ISSUE TITLE
Support Match

### ISSUE THREAD

**Issue by tanishiking** [tanishiking/scala-wasm#35]

**Comment by SethTisue** [comment]
@sjrd partly implemented this in front of our eyes at Scalar

**Comment by sjrd** [comment]
It was pretty basic, though, and assumed the case labels were consecutive integers starting from 0. I can share the snippet tomorrow as a good start for implementing the real thing.

**Comment by sjrd** [comment]
Here is what we did: https://github.com/tanishiking/scala-wasm/compare/main...sjrd:scala-wasm:live-coding-match
