### ISSUE TITLE
Support `IsInstanceOf[Array[T]]` / `AsInstanceof[Array[T]]`

### ISSUE THREAD

**Issue by tanishiking** [tanishiking/scala-wasm#40]
https://github.com/tanishiking/scala-wasm/blob/949f7f4fb4a0d27d6208c263859aa9df529a373e/wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala#L1100-L1102

https://github.com/tanishiking/scala-wasm/blob/949f7f4fb4a0d27d6208c263859aa9df529a373e/wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala#L1160-L1162

They will be required to support collections such as `Seq` or defining case classes.

Now, we can support those instructions thanks to `typedata` ?

**Comment by sjrd** [comment]
I have a wip branch for this, which I started yesterday: https://github.com/tanishiking/scala-wasm/compare/main...sjrd:scala-wasm:array-behavior-as-object

It's tricky as it requires a number of changes, but I'll probably finish it today.
